# Generated by Django 5.0.1 on 2024-01-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fabricante',
            new_name='Cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome_fabricante',
            new_name='nome_cliente',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='fabricante',
            new_name='cliente',
        ),
    ]
