# Generated by Django 5.0.1 on 2024-01-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_fabricante_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='idade_cliente',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
